package embeddednzbget

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"path/filepath"
	"strings"
)

// NewsProvider holds the operator-supplied Usenet provider credentials
// NZBGet uses to fetch articles. Cross-cuts to the runtime Config —
// kept here so the supervisor doesn't depend on runtime/.
type NewsProvider struct {
	Host        string
	Port        int
	SSL         bool
	Username    string
	Password    string
	Connections int // 0 → 8 by default
}

// rpcCredentials holds the per-start credentials NZBGet uses to gate
// its JSON-RPC port. Generated fresh each Start() so a process that
// outlives a Stop() doesn't leak access to its replacement.
type rpcCredentials struct {
	Username string
	Password string
}

// newRPCCredentials mints 16-byte random user/pass. They're only ever
// used over localhost loopback so 128 bits is overkill but cheap.
func newRPCCredentials() (rpcCredentials, error) {
	user := make([]byte, 8)
	pass := make([]byte, 16)
	if _, err := rand.Read(user); err != nil {
		return rpcCredentials{}, err
	}
	if _, err := rand.Read(pass); err != nil {
		return rpcCredentials{}, err
	}
	return rpcCredentials{
		Username: "silo-" + hex.EncodeToString(user),
		Password: hex.EncodeToString(pass),
	}, nil
}

// generateConf renders a minimal nzbget.conf wired to the operator's
// Usenet provider, listening only on loopback, with paths anchored
// under the supervisor's working directory. Returns the file contents
// ready to write.
//
// Most NZBGet settings are left at their defaults — we only set what
// the daemon won't start without, what differs from defaults, and the
// security-relevant knobs (loopback bind, generated creds, no anon
// access). A future operator who needs to tune NZBGet beyond this can
// install standalone NZBGet and switch to download_mode=nzbget.
func generateConf(layout pathLayout, provider NewsProvider, creds rpcCredentials, port int) string {
	connections := provider.Connections
	if connections <= 0 {
		connections = 8
	}
	encryption := "no"
	if provider.SSL {
		encryption = "yes"
	}
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Auto-generated by silo-plugin-audiobook-requests. Do not")
	w("# edit by hand; the supervisor regenerates on every restart.")
	w("MainDir=%s", layout.MainDir)
	w("DestDir=${MainDir}/dst")
	w("InterDir=${MainDir}/inter")
	w("TempDir=${MainDir}/tmp")
	w("QueueDir=${MainDir}/queue")
	w("NzbDir=${MainDir}/nzb")
	w("LogFile=${MainDir}/nzbget.log")
	w("ConfigTemplate=") // we don't ship one; suppress the warning
	w("WebDir=%s", filepath.Join(layout.BinDir, "webui"))
	w("CertStore=%s", layout.CertStore)
	w("CertCheck=yes")
	w("UnrarCmd=%s", filepath.Join(layout.BinDir, "unrar-x86_64"))
	w("SevenZipCmd=%s", filepath.Join(layout.BinDir, "7za-x86_64"))
	// Loopback-only control surface. The plugin process is the only
	// client; anything else trying to reach NZBGet means the operator's
	// container is misconfigured.
	w("ControlIP=127.0.0.1")
	w("ControlPort=%d", port)
	w("ControlUsername=%s", creds.Username)
	w("ControlPassword=%s", creds.Password)
	w("FormAuth=no")
	w("AuthorizedIP=")
	w("DaemonUsername=")
	// One news provider entry. Multiple providers + backup-tier
	// scheduling are out of scope for the embedded mode — operators
	// who need that should run standalone NZBGet.
	w("Server1.Active=yes")
	w("Server1.Name=primary")
	w("Server1.Level=0")
	w("Server1.Optional=no")
	w("Server1.Group=1")
	w("Server1.Host=%s", provider.Host)
	w("Server1.Port=%d", provider.Port)
	w("Server1.Username=%s", provider.Username)
	w("Server1.Password=%s", provider.Password)
	w("Server1.JoinGroup=no")
	w("Server1.Encryption=%s", encryption)
	w("Server1.Cipher=")
	w("Server1.Connections=%d", connections)
	w("Server1.Retention=0")
	w("Server1.IpVersion=auto")
	w("Server1.Notes=")
	// Output / behavior tuning. Foreground server mode + plain text
	// log so we can stream it through hclog.
	w("OutputMode=loggable")
	w("WriteLog=append")
	w("RotateLog=3")
	w("UpdateInterval=200")
	w("UrlConnections=4")
	w("ContinuePartial=yes")
	w("DirectWrite=yes")
	w("WriteBuffer=0")
	w("NzbDirInterval=0")
	w("DiskSpace=250")
	// Post-processing: we want unrar + par2 repair on by default
	// (that's the whole point of using NZBGet over a from-scratch
	// downloader).
	w("ParCheck=auto")
	w("ParRepair=yes")
	w("ParScan=auto")
	w("ParQuick=yes")
	w("ParBuffer=16")
	w("ParThreads=0")
	w("Unpack=yes")
	w("UnpackCleanupDisk=yes")
	w("UnpackPauseQueue=no")
	w("HealthCheck=delete")
	w("ParPauseQueue=no")
	w("ScriptPauseQueue=no")
	// Categories: one category that lines up with what the consumer
	// passes on append.
	w("Category1.Name=audiobooks")
	w("Category1.DestDir=")
	w("Category1.Unpack=yes")
	w("Category1.ExtCleanup=")
	w("Category1.Aliases=")
	w("Category1.PostScript=")
	return b.String()
}
